version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/chrillep/vinyl-catalog"
  dependencies_vendored = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true

[[transformers]]
name = "prettier"
enabled = true